version: "3.5"

services:
  server:
    build: .
    restart: always
    networks:
      - default
    ports:
      - "80"
    volumes:
      - ${PWD}/cdn:/app/cdn
      - ${PWD}/zip:/app/zip
      # - ${PWD}/cdn.log:/app/cdn.log
      # - ${PWD}/cdn.db:/app/cdn.db
networks:
  default:
    name: bridge
    external: true
